### PR TITLE
french locales file

### PR DESCRIPTION
**Pull request by pronoiak**
did my best !

### CODE REVIEW

**Comment by josephlacey** [comment]
The failures on the tests here are expected actually since this file is changing the names of buttons and links, e.g.

> entities/add_relationship layout is expected to have css "h2" with text "Create a new relationship"
>     Failure/Error: expect(rendered).to have_css(...)
>      expected to find css "h2" with text "Create a new relationship" but there were no matches. Also found "\n            Créer une nouvelle relation\n          ", which matched the selector but not all filters. 

Looks like we need to rewrite the tests to be localized. 

Here's the full list of failures from this run,

```
rspec ./spec/features/dashboard_spec.rb:11 # home/dashboard with a logged-out user user clicks login and is taken to the dashboard
rspec ./spec/features/dashboard_spec.rb:55 # home/dashboard Using the navigation bar on top of the basic as a regular user has nav dropdown
rspec ./spec/features/dashboard_spec.rb:76 # home/dashboard explore contains links to maps, lists, tags and edits
rspec ./spec/features/deletion_requests/entity_spec.rb:28 # Entity deletion request & review requesting a deletion as a non-admin shows the deletion request page
rspec ./spec/features/deletion_requests/entity_spec.rb:32 # Entity deletion request & review requesting a deletion as a non-admin shows information about the entity to be deleted
rspec ./spec/features/deletion_requests/entity_spec.rb:36 # Entity deletion request & review requesting a deletion as a non-admin shows submit button and text area
rspec ./spec/features/deletion_requests/entity_spec.rb:58 # Entity deletion request & review requesting a deletion as a non-admin submitting request does not delete the entity
rspec ./spec/features/deletion_requests/entity_spec.rb:62 # Entity deletion request & review requesting a deletion as a non-admin submitting request creates a pending deletion request
rspec ./spec/features/deletion_requests/entity_spec.rb:70 # Entity deletion request & review requesting a deletion as a non-admin submitting request redirects to the dashboard
rspec ./spec/features/edit_entity_spec.rb:21 # edit entity page updating an entity's fields submitting a new short description and selecting 'just cleaning up'
rspec ./spec/features/edit_entity_spec.rb:40 # edit entity page filling out business data user adds business financial details
rspec ./spec/features/edit_entity_spec.rb:65 # edit entity page changing start date setting date to "1 May, 1970"
rspec ./spec/features/edit_entity_spec.rb:90 # edit entity page adding new references the url is not yet in the database
rspec ./spec/features/edit_entity_spec.rb:106 # edit entity page adding new references when the url already exists as a document
rspec ./spec/features/edit_entity_spec.rb:127 # edit entity page external links submitting a new wikipedia link and new twitter
rspec ./spec/features/edit_entity_spec.rb:154 # edit entity page external links modifying existing external link changing the wikipedia page name
rspec ./spec/features/edit_entity_spec.rb:167 # edit entity page external links modifying existing external link deleting existing text
rspec ./spec/features/entity_page_spec.rb:233 # Entity Page sidebar with an anonymous user without tags has sections
rspec ./spec/features/entity_page_spec.rb:264 # Entity Page sidebar with an anonymous user with external links viewing external links section
rspec ./spec/features/entity_page_spec.rb:283 # Entity Page sidebar with an anonymous user with network maps has a network maps section
rspec ./spec/features/entity_page_spec.rb:407 # Entity Page navigation tabs has tabs for every subpage
rspec ./spec/features/entity_page_spec.rb:413 # Entity Page navigation tabs defaults to relationships tab
rspec ./spec/features/homepage_spec.rb:18 # Homepage visiting the home page anonymous user visiting the home page
rspec ./spec/features/js/adding_an_entity_relationship_spec.rb:21 # Adding an entity relationship user visits person page, searches for other person and creates a relationship
rspec ./spec/features/js/new_entity_page_spec.rb:9 # New entity page with a logged in user user tries to create an entity but sees validation errors
rspec ./spec/features/merging_spec.rb:32 # Merging entities navigating to merge pages from an entity profile page as a non-admin user navigates to search page from `merge` action button
rspec ./spec/features/merging_spec.rb:41 # Merging entities navigating to merge pages from an entity profile page as an admin navigates to search page from `merge` action button
rspec ./spec/features/new_entity_spec.rb:26 # /entities/new creating a new entity when user is an editor can create a new person
rspec ./spec/features/signup_spec.rb:12 # Signing up for an account User visits join page
rspec ./spec/features/signup_spec.rb:79 # Signing up for an account Attempting to signup with a username that is already taken Shows error message regarding the username
rspec ./spec/features/user_settings_spec.rb:51 # User Settings setting language to Spanish
rspec ./spec/views/entities/_actions.html.erb_spec.rb:27 # entities/actions when user is an advanced user org page is expected to have css "a" with text "remove"
rspec ./spec/views/entities/_actions.html.erb_spec.rb:28 # entities/actions when user is an advanced user org page is expected to have css "a" with text "add bulk"
rspec ./spec/views/entities/_actions.html.erb_spec.rb:34 # entities/actions when user is an advanced user person page is expected to have css "a" with text "remove"
rspec ./spec/views/entities/_actions.html.erb_spec.rb:35 # entities/actions when user is an advanced user person page is expected to have css "a" with text "add bulk"
rspec ./spec/views/entities/add_relationships.html.erb_spec.rb:12 # entities/add_relationship layout is expected to have css "h2" with text "Create a new relationship"
```

**Comment by josephlacey** [comment]
Per @aepyornis, should add french to this list of available locales,

https://github.com/public-accountability/littlesis-rails/blob/main/app/controllers/application_controller.rb#L4

And here are some additional translations that happen in javascript that need french added,

https://github.com/public-accountability/littlesis-rails/blob/main/app/javascript/controllers/subcategory_translation_controller.js

**Comment by josephlacey** [comment]
Closing this PR in favor of #1693 to pull all the commits together for automated testing.

**Comment by pronoiak** [comment]
> Per @aepyornis, should add french to this list of available locales,
> https://github.com/public-accountability/littlesis-rails/blob/main/app/controllers/application_controller.rb#L4

Adding "fr" to the availables locales does not translate the profile header texts, and results in many error, one of them is that it became impossible to log in again, I had to change the code to remove the "fr".

**Comment by aepyornis** [comment]
@pronoiak @josephlacey  I think this is because the [default user language settings is set to english](https://github.com/public-accountability/littlesis-rails/blob/main/app/utility/user_settings.rb#L7) and this setting currently take precedence over the language header.

We need to add french to the [user settings form](https://github.com/public-accountability/littlesis-rails/blob/main/app/controllers/application_controller.rb#L156/).

**Pull request closed without merging**
