### PR TITLE
Clear entity caches on links refresh

### PR DESCRIPTION
**Pull request by robjlucas**

### CODE REVIEW

**Comment by robjlucas** [comment]
@aepyornis I couldn't think of a good way of testing the job callback, given the apparent requirement of parallel threads, timed precisely in relation to each other, but it's a simple enough solution. Note that though on the face of it it may seem strange to touch the entity models when updating relationships, these are already updated by a callback just before the job runs anyway, to maintain link counts, so this touch will simply adjust that timestamp slightly in order to correct the caching problem.

**Comment by aepyornis** [comment]
I think we should wait on this one until we understand the situation a little bit more, especially given that I already introduced one ugly hack here 75c8159e136837380dc4b760509c766a7240957d haha

There's a two things going on that I'd like to solve:

1. If many edits happen around the same time a whole queue of `LinksViewRefereshJob` will appear.  Even though we can run jobs in parallel, I think postgres can only perform one `refresh` command at a time. If each one takes 20-30 seconds, even just 10 edits happening at once could cause a noticeable delay of many minutes for the last view edits to appear on profile pages. We have bulk tools that can create hundreds of relationships at once.

This also seems like a somewhat wasteful use of delayed_job and postgres resources, maybe we should look into running this task every x minutes? Although then we would have to consider how long is acceptable for a user to wait to see their newly-created relationship on the profile page.

2. Our entity views use `cache`  with  `@entity.cache_key_with_version` all over the place. This really drastically helps with expensive views on large profile pages, which are, of course, the most popular.  The timestamp is also used to indicate when the edits occurred, so I'm not crazy about the idea of changing the timestamps just to expire caches (I've confused plenty of people over the years with various bugs regarding timestamps) 

Maybe we can consider solving this by refactoring a lot of sql so that we don't have to use a links table at all. I think there could be postgres tricks -- or perhaps caching of links already aggregated per entity in a table.

**Comment by robjlucas** [comment]
> I think we should wait on this one until we understand the situation a little bit more, especially given that I already introduced one ugly hack here [75c8159](https://github.com/public-accountability/littlesis-rails/commit/75c8159e136837380dc4b760509c766a7240957d) haha
> 
> There's a two things going on that I'd like to solve:
> 
>     1. If many edits happen around the same time a whole queue of `LinksViewRefereshJob` will appear.  Even though we can run jobs in parallel, I think postgres can only perform one `refresh` command at a time. If each one takes 20-30 seconds, even just 10 edits happening at once could cause a noticeable delay of many minutes for the last view edits to appear on profile pages. We have bulk tools that can create hundreds of relationships at once.

I had wondered about this sort of thing myself, but the bulk tools issue had escaped my notice, and this seems like a real problem with triggering these jobs from a callback on `Relationship`.

> This also seems like a somewhat wasteful use of delayed_job and postgres resources, maybe we should look into running this task every x minutes? Although then we would have to consider how long is acceptable for a user to wait to see their newly-created relationship on the profile page.

This seems like a sensible way of avoiding the bulk issue noted above.

>     1. Our entity views use `cache`  with  `@entity.cache_key_with_version` all over the place. This really drastically helps with expensive views on large profile pages, which are, of course, the most popular.  The timestamp is also used to indicate when the edits occurred, so I'm not crazy about the idea of changing the timestamps just to expire caches (I've confused plenty of people over the years with various bugs regarding timestamps)

Yes, I thought about this issue myself and had similar concerns, but one consideration is that any entity that gets updated by the `touch_all` here will by definition already have been updated in the last 30 seconds or however long it takes the job to run, so it's not really distorting the timestamps much; entity timestamps are already updated by callbacks from `Relationship` in any case, so already don't correspond exactly to actual updates directly on `Entity`. An alternative that I considered is that you can of course monkey-patch the cache-key timestamp logic quite easily; one could maintain a separate timestamp specifically for the purpose of caching in order to keep `updated_at` strictly for actual updates to `Entity`.

> Maybe we can consider solving this by refactoring a lot of sql so that we don't have to use a links table at all. I think there could be postgres tricks -- or perhaps caching of links already aggregated per entity in a table.

**Comment by robjlucas** [comment]
Ultimately, we should be pragmatic with this. Though it might seem more "correct" to have `Link` as a view model, if it's just making things more complicated and inefficient, then this might be a case where the seemingly kludgier solution of just sticking the data in a normal table is actually the better.

**Pull request closed without merging**
