### PR TITLE
Client side entity name validation

### PR DESCRIPTION
**Pull request by robjlucas**
Calls the API for entity validation on form input `blur` and presents the result with the same formatting we would use for a server-side validation.

This is a general-purpose method and will work for anything that can be validated server-side. In the present case, we specify only the `name` attribute for validation.

Screenshot 2020-04-01 at 21 01 18

### CODE REVIEW

**Comment by robjlucas** [comment]
@aepyornis I can't see any refactoring of the function codeclimate is complaining about which doesn't add more complexity. Any suggestions?

**Comment by aepyornis** [comment]
> @aepyornis I can't see any refactoring of the function codeclimate is complaining about which doesn't add more complexity. Any suggestions?

Ah, I won't worry about it. I actually wish I could figure how to set the codeclimate check to pass when there are only a couple of issues to fix (you can manually).

**Comment by robjlucas** [comment]
> @robjlucas This looks great. I have one change to request, although it's totally open for discussion if you strongly think otherwise.
> 
> The `ApiController ` and `/api` are our public API routes. (described here https://littlesis.org/api) and I think we ought to keep the ApiController only for publicly accessible and documented API routes. `/api/entities/validate` can become `/entities/validate` and exist on the `EntitiesController`. However, that controller is crowed and disorganized, so I understand the motivation to use /api for this kind of request. We should refactor that controller at some point ( the NYS matching and image routes don't need to be there)
> 
> The api routes also work somewhat differently: they are rate-limited and use a different base controller. We used to have API tokens, but I recently disabled them.
> 
> In the longer term, we should consider a better organization strategy for our controllers to deal with html pages vs json requests.

@aepyornis sure—that makes sense to me. Didn't realise you had a rigourous distinction on this, but yes best to work with the way you already divide these up. I'll move it over.

**Comment by robjlucas** [comment]
> > @robjlucas This looks great. I have one change to request, although it's totally open for discussion if you strongly think otherwise.
> > The `ApiController ` and `/api` are our public API routes. (described here https://littlesis.org/api) and I think we ought to keep the ApiController only for publicly accessible and documented API routes. `/api/entities/validate` can become `/entities/validate` and exist on the `EntitiesController`. However, that controller is crowed and disorganized, so I understand the motivation to use /api for this kind of request. We should refactor that controller at some point ( the NYS matching and image routes don't need to be there)
> > The api routes also work somewhat differently: they are rate-limited and use a different base controller. We used to have API tokens, but I recently disabled them.
> > In the longer term, we should consider a better organization strategy for our controllers to deal with html pages vs json requests.
> 
> @aepyornis sure—that makes sense to me. Didn't realise you had a rigourous distinction on this, but yes best to work with the way you already divide these up. I'll move it over.

... unless, that is, there might be a case for making this functionality available in the public API and documenting it accordingly. I could imagine entity validation might have general uses. What do you think?

**Comment by aepyornis** [comment]
> ... unless, that is, there might be a case for making this functionality available in the public API and documenting it accordingly. I could imagine entity validation might have general uses. What do you think @aepyornis ?

There's certainly no harm in having it available to the public, but I don't think it would be very useful since our public API is read-only. I even disabled the api tokens -- there's currently no authorization needed. We don't allow people to write applications that add or update LittleSis entities. The route might be useful for some of our internal tools (such as our chrome extension). Ideally we would have a better documented and organized internal API.

**Comment by robjlucas** [comment]
> > ... unless, that is, there might be a case for making this functionality available in the public API and documenting it accordingly. I could imagine entity validation might have general uses. What do you think @aepyornis ?
> 
> There's certainly no harm in having it available to the public, but I don't think it would be very useful since our public API is read-only. I even disabled the api tokens -- there's currently no authorization needed. We don't allow people to write applications that add or update LittleSis entities. The route might be useful for some of our internal tools (such as our chrome extension). Ideally we would have a better documented and organized internal API.

Makes sense @aepyornis. Have just moved it out of the API as discussed.

**Pull request merged**
